drop table if exists posts CASCADE;
create table member
(
    postSeq   bigint generated by default as identity,
    title     varchar(255),
    content   varchar(255),
    writer    varchar(255),
    regDate   DATE,
    postLevel integer(255),
    useYN     boolean(255),
    primary key (postSeq)
);